name: 'Build Action test'
description: 'Repeat message back with the time'
inputs:
  repo:
    description: 'Repository containing the Dockerfile to be built'
    required: true
    default: ''
outputs:
  return:
    description: 'Output of ls'
runs:
  using: 'node12'
  main: 'index.js'

